# Generated by Django 4.0.2 on 2022-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_file_upload_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
